'use strict';
const $ = id => document.getElementById(id);
const state = {data:[],summary:{series:[]},history:[],messages:[],conversationId:null,page:1,busy:false,health:null,preview:false,token:sessionStorage.getItem('blog-access-token')||''};
const base=(window.APP_CONFIG?.API_BASE_URL||'').replace(/\/$/,'');
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500)}
function showNotice(message,retry=false){$('notice').textContent=message;$('notice').hidden=!message;if(retry){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='연결 다시 시도';button.onclick=initialize;$('notice').append(button)}}
function view(name){document.querySelectorAll('.view').forEach(el=>{el.hidden=el.id!==`view-${name}`;el.classList.toggle('active',!el.hidden)});document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===name));$('page-label').textContent={write:'글 작성',data:'데이터 관리',history:'이전 대화',settings:'연결 설정'}[name];if(name==='history')loadHistory();window.scrollTo({top:0,behavior:'smooth'})}
async function api(path,options={}){const initialRead=path==='/health'||path==='/api/bootstrap';for(let attempt=0;attempt<(initialRead?2:1);attempt++){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),path==='/api/chat'?70000:initialRead?90000:60000);try{const res=await fetch(base+path,{...options,signal:controller.signal,headers:{'Content-Type':'application/json',...(state.token?{'Authorization':`Bearer ${state.token}`} : {}),...options.headers}});const body=await res.json().catch(()=>({}));if(!res.ok){if(res.status===401)view('settings');const error=Error(typeof body.detail==='string'?body.detail:(Array.isArray(body.detail)?'입력 내용을 확인해 주세요.':'요청을 처리하지 못했습니다.'));error.retryable=res.status===502||res.status===503||res.status===504;throw error}return body}catch(error){const retryable=error.name==='AbortError'||error instanceof TypeError||error.retryable;if(initialRead&&attempt===0&&retryable){showNotice('무료 서버 또는 Firestore가 시작 중입니다. 잠시 후 자동으로 다시 연결합니다.');await new Promise(resolve=>setTimeout(resolve,2500));continue}if(error.name==='AbortError')throw Error('응답이 지연되고 있습니다. 연결 다시 시도를 눌러 주세요.');throw error}finally{clearTimeout(timeout)}}}
const sendJSON=(path,body,method='POST',headers={})=>api(path,{method,body:JSON.stringify(body),headers});
function requireLive(){if(state.preview){toast('현재 화면 미리보기입니다. 앱 서버를 실행하면 저장과 AI 연결을 사용할 수 있습니다.');return false}return true}
function safeText(tag,text,className){const el=document.createElement(tag);el.textContent=text;if(className)el.className=className;return el}
function summarizeLocal(rows){const series=['visits','pageviews'].map(metric=>{const points=rows.filter(r=>r.metric===metric).sort((a,b)=>a.date.localeCompare(b.date));if(!points.length)return null;const values=points.map(r=>r.value),recent=values.slice(-7).reduce((a,b)=>a+b,0),previous=values.slice(-14,-7).reduce((a,b)=>a+b,0);return{metric,label:metric==='visits'?'방문 횟수':'조회수',unit:metric==='visits'?'회':'건',count:points.length,total:values.reduce((a,b)=>a+b,0),average:values.reduce((a,b)=>a+b,0)/values.length,min:Math.min(...values),max:Math.max(...values),start:points[0].date,end:points.at(-1).date,recent7:recent,previous7:previous,trend:recent>previous?'증가':recent<previous?'감소':'유지',points}}).filter(Boolean);return{count:rows.length,unique_days:new Set(rows.map(r=>r.date)).size,series}}
let initializing=false;
async function initialize(){if(initializing)return;initializing=true;showNotice('서버에 연결하고 있습니다. 무료 서버의 첫 접속은 잠시 걸릴 수 있어요.');try{if(window.APP_CONFIG?.STATIC_PREVIEW){state.preview=true;state.data=(window.APP_CONFIG.INLINE_SEED || await fetch('/static/seed.json').then(r=>r.json())).map((r,i)=>({...r,id:`preview-${i}`}));state.summary=summarizeLocal(state.data);showNotice('화면 미리보기 · 가상 샘플 데이터 180개를 표시합니다. 저장과 AI 기능은 서버 실행 후 사용할 수 있습니다.');$('connection-badge').textContent='샘플 데이터 · 화면 미리보기';renderAll();renderHealth();return}state.health=await api('/health');$('connection-badge').textContent=state.health.ai_configured?'AI 설정됨':'AI 연결 필요';renderHealth();await refresh();showNotice(state.health.storage==='sqlite'?'로컬 미리보기 저장소를 사용 중입니다. 과제 제출 전 연결 설정에서 Firestore를 연결해 주세요.':'')}catch(error){showNotice(`연결을 완료하지 못했습니다. ${error.message}`,true);$('connection-badge').textContent='연결 확인 필요';renderHealth()}finally{initializing=false}}
async function refresh(){const result=await api('/api/bootstrap');state.data=result.data;state.summary=result.summary;renderAll()}
function renderAll(){renderStats();renderChart();renderData()}
function renderStats(){const visits=state.summary.series.find(s=>s.metric==='visits'),views=state.summary.series.find(s=>s.metric==='pageviews');const entries=[['저장된 관측값',`${state.summary.count||0}개`,`${state.summary.unique_days||0}일 · 지표 2종`],['방문 횟수',visits?`${visits.total}회`:'—',visits?`일평균 ${Number(visits.average).toFixed(2)}회`:'기록을 추가해 주세요'],['조회수',views?`${views.total}건`:'—',views?`일평균 ${Number(views.average).toFixed(2)}건`:'기록을 추가해 주세요'],['기록 기간',visits?`${visits.start.slice(5).replace('-','.')}–${visits.end.slice(5).replace('-','.')}`:'—',visits?`${visits.start.slice(0,4)}년 · 마지막 관측일까지`:'데이터 없음']];$('stats-strip').replaceChildren(...entries.map(([title,value,note])=>{const el=safeText('div','','stat');el.append(safeText('span',title),safeText('strong',value),safeText('small',note));return el}))}
function renderChart(){const s=state.summary.series.find(s=>s.metric===$('chart-metric').value);$('chart').replaceChildren();if(!s){$('trend-text').textContent='데이터를 가져오거나 새 기록을 추가해 주세요.';return}const points=s.points.slice(-30),max=Math.max(1,...points.map(p=>p.value));const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 260 130');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${s.label} 최근 ${points.length}일 그래프, 최대 ${max}${s.unit}`);const path=document.createElementNS(svg.namespaceURI,'polyline');path.setAttribute('points',points.map((p,i)=>`${8+i*244/Math.max(1,points.length-1)},${118-p.value/max*100}`).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#087d79');path.setAttribute('stroke-width','3');path.setAttribute('stroke-linejoin','round');svg.append(path);const labels=safeText('div','','chart-labels');labels.append(safeText('span',points[0].date.slice(5)),safeText('span',points.at(-1).date.slice(5)));$('chart').append(svg,labels);$('trend-text').textContent=s.recent7===null? '최근 14일의 일부 기록이 없어 추세를 계산하지 않았습니다.':`최근 7일 ${s.recent7}${s.unit}, 이전 7일 ${s.previous7}${s.unit} · ${s.trend}`}
function renderData(){const filter=$('data-filter').value;const rows=state.data.filter(r=>filter==='all'||r.metric===filter).sort((a,b)=>b.date.localeCompare(a.date)||a.metric.localeCompare(b.metric));const totalPages=Math.max(1,Math.ceil(rows.length/15));state.page=Math.min(state.page,totalPages);$('data-count').textContent=`총 ${rows.length}개 기록`;$('page-number').textContent=`${state.page} / ${totalPages}`;$('prev-page').disabled=state.page<=1;$('next-page').disabled=state.page>=totalPages;$('data-rows').replaceChildren(...rows.slice((state.page-1)*15,state.page*15).map(row=>{const tr=document.createElement('tr');tr.append(safeText('td',row.date),safeText('td',row.metric==='visits'?'방문 횟수':'조회수'),safeText('td',row.value,'number'),safeText('td',row.memo,'memo-cell'));const actions=document.createElement('td'),edit=safeText('button','수정','table-button'),del=safeText('button','삭제','table-button danger');edit.onclick=()=>editData(row);del.onclick=()=>deleteData(row);actions.append(edit,del);tr.append(actions);return tr}));if(!rows.length){const tr=document.createElement('tr'),td=safeText('td','아직 기록이 없습니다. 샘플 데이터를 가져오거나 새 기록을 추가해 주세요.','empty');td.colSpan=5;tr.append(td);$('data-rows').append(tr)}}
function editData(row){if(!requireLive())return;$('record-id').value=row.id;$('data-date').value=row.date;$('data-metric').value=row.metric;$('data-value').value=row.value;$('data-memo').value=row.memo;$('save-data').textContent='수정 저장';$('cancel-edit').hidden=false;$('data-date').focus()}
function resetForm(){$('data-form').reset();$('record-id').value='';$('save-data').textContent='추가';$('cancel-edit').hidden=true}
async function deleteData(row){if(!requireLive()||!confirm(`${row.date} ${row.metric==='visits'?'방문 횟수':'조회수'} 기록을 삭제할까요?`))return;try{await api(`/api/data/${encodeURIComponent(row.id)}`,{method:'DELETE'});await refresh();toast('기록을 삭제했습니다.')}catch(error){toast(error.message)}}
function renderMessages(){if(!state.messages.length){$('messages').replaceChildren(safeText('div','새로운 주제나 질문으로 대화를 시작해 주세요.','empty'));return}$('messages').replaceChildren(...state.messages.map(message=>{const box=safeText('div','',`message ${message.role}`);box.append(safeText('div',message.role==='user'?'나':'블로그 비서','message-label'),safeText('div',message.content,'message-content'));if(message.role==='assistant'){const copy=safeText('button','본문 복사','copy-button');copy.onclick=()=>copyText(message.content);box.append(copy)}return box}));$('messages').scrollTop=$('messages').scrollHeight}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('본문을 복사했습니다.')}catch{toast('복사 권한이 없습니다. 본문을 선택해 복사해 주세요.')}}
async function loadHistory(){if(state.preview){$('history-list').replaceChildren(safeText('div','앱 서버를 실행하면 대화를 저장하고 불러올 수 있습니다.','card empty'));return}try{state.history=await api('/api/conversations');$('history-list').replaceChildren(...state.history.map(row=>{const card=safeText('article','','card history-item'),info=document.createElement('div'),buttons=document.createElement('div');info.append(safeText('h3',row.title),safeText('p',`${new Date(row.updated_at).toLocaleString('ko-KR')} · 메시지 ${row.message_count}개`));const load=safeText('button','불러오기','primary'),del=safeText('button','삭제','secondary danger');load.onclick=()=>loadConversation(row.id);del.onclick=async()=>{if(!confirm('이 대화를 삭제할까요?'))return;try{await api(`/api/conversations/${row.id}`,{method:'DELETE'});if(state.conversationId===row.id)newChat();await loadHistory();toast('대화를 삭제했습니다.')}catch(error){toast(error.message)}};buttons.append(load,del);card.append(info,buttons);return card}));if(!state.history.length)$('history-list').append(safeText('div','저장된 대화가 아직 없습니다. 첫 글을 요청하거나 기존 대화를 저장해 보세요.','card empty'))}catch(error){toast(error.message)}}
async function loadConversation(id){if(state.busy){toast('답변이 완료된 후 대화를 바꿀 수 있습니다.');return}try{const row=await api(`/api/conversations/${id}`);state.conversationId=id;state.messages=row.messages;renderMessages();view('write');toast('대화를 불러왔습니다. 이어서 질문할 수 있어요.')}catch(error){toast(error.message)}}
function newChat(){if(state.busy){toast('답변을 작성 중입니다. 잠시 기다려 주세요.');return}state.conversationId=null;state.messages=[];renderMessages();$('prompt').value=''}
function renderHealth(){const h=state.health;const entries=[['AI 서비스',h?.provider==='openai'?'OpenAI GPT':'Google Gemini'],['모델',h?.model||'서버 연결 후 확인'],['AI',h?.ai_configured?'키 설정됨 · 실제 요청 확인 필요':'연결 필요'],['저장소',h?.storage==='firestore'?'Firestore 설정됨':state.preview?'서버 미실행':'로컬 SQLite (개발용)'],['접속 API',base||'현재 서버 (동일 주소)']];$('health-list').replaceChildren(...entries.flatMap(([a,b])=>[safeText('dt',a),safeText('dd',b)]));$('local-settings').hidden=!h?.local_setup;$('ai-provider').value=h?.provider||'gemini';$('preview-explanation').textContent=state.preview?'현재는 가상 샘플 데이터를 표시하는 읽기 전용 화면입니다. 백엔드 실행 후 기능을 사용할 수 있습니다.':'키 존재 여부만 표시합니다. 실제 연결 결과는 데이터 조회와 글 작성으로 확인합니다.'}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.prompt;if(b.dataset.category)$('category').value=b.dataset.category;$('prompt').focus()});$('new-chat').onclick=newChat;$('chart-metric').onchange=renderChart;$('data-filter').onchange=()=>{state.page=1;renderData()};$('prev-page').onclick=()=>{state.page--;renderData()};$('next-page').onclick=()=>{state.page++;renderData()};$('cancel-edit').onclick=resetForm;$('retry').onclick=initialize;$('refresh-history').onclick=loadHistory;
$('chat-form').onsubmit=async event=>{event.preventDefault();if(!requireLive()||state.busy)return;const message=$('prompt').value.trim();if(!message){toast('주제나 질문을 입력해 주세요.');return}state.busy=true;$('send').disabled=true;const prior=state.messages.slice();state.messages.push({role:'user',content:message});renderMessages();const loading=safeText('div','','loading');loading.append(safeText('span','','spinner'),safeText('span','내 블로그 데이터를 참고해 작성하고 있어요…'));$('messages').append(loading);try{const result=await sendJSON('/api/chat',{message,conversation_id:state.conversationId,category:$('category').value,tone:$('tone').value,length:Number($('length').value)});state.conversationId=result.conversation_id;state.messages.push({role:'assistant',content:result.answer});$('prompt').value='';renderMessages();toast('답변과 대화를 저장했습니다.')}catch(error){state.messages=prior;renderMessages();toast(error.message)}finally{state.busy=false;$('send').disabled=false;loading.remove()}};
$('data-form').onsubmit=async event=>{event.preventDefault();if(!requireLive())return;const id=$('record-id').value;const payload={date:$('data-date').value,value:Number($('data-value').value),memo:$('data-memo').value,metric:$('data-metric').value};try{await sendJSON(id?`/api/data/${encodeURIComponent(id)}`:'/api/data',payload,id?'PUT':'POST');resetForm();await refresh();toast(id?'수정 내용을 저장했습니다.':'새 기록을 추가했습니다.')}catch(error){toast(error.message)}};
$('seed-data').onclick=async()=>{if(!requireLive())return;try{$('seed-data').disabled=true;const r=await sendJSON('/api/data-import',{});await refresh();toast(`${r.added}개를 가져왔습니다. 기존 기록은 유지했습니다.`)}catch(error){toast(error.message)}finally{$('seed-data').disabled=false}};
$('manual-form').onsubmit=async event=>{event.preventDefault();if(!requireLive())return;try{await sendJSON('/api/conversations',{title:$('manual-title').value,messages:[{role:'assistant',content:$('manual-content').value}]});$('manual-form').reset();await loadHistory();toast('대화를 저장했습니다.')}catch(error){toast(error.message)}};
$('access-form').onsubmit=event=>{event.preventDefault();state.token=$('access-token').value;sessionStorage.setItem('blog-access-token',state.token);$('access-token').value='';initialize()};
$('setup-form').onsubmit=async event=>{event.preventDefault();const file=$('firebase-file').files[0];if(file&&file.size>12000){toast('서비스 계정 JSON 파일 크기를 확인해 주세요.');return}try{await sendJSON('/local/setup',{ai_provider:$('ai-provider').value,gemini_api_key:$('gemini-key').value,openai_api_key:$('openai-key').value,firebase_service_account_json:file?await file.text():''},'POST',{'X-Local-Setup':'1'});$('setup-form').reset();toast('연결 정보를 저장했습니다.');await initialize()}catch(error){toast(error.message)}};
$('export-data').onclick=()=>{const cols=['date','value','memo','metric'];const csv='\ufeff'+[cols.join(','),...state.data.map(r=>cols.map(k=>'"'+String(r[k]??'').replaceAll('"','""').replace(/^[=+@-]/,"'$&")+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='blog-data.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
initialize();
